### ISSUE TITLE
Update dinglehopper version in ocrd_all

### ISSUE THREAD

**Issue by mikegerber** [qurator-spk/dinglehopper#22]
- [ ] Wait for #10 (Display image)
- [ ] Wait for #9 (Display segment ID)
- [ ] Wait for #24 (Release on PyPI)

**Comment by mikegerber** [comment]
ocrd_all has since updated, going to close this. (Open checkbox items will be addressed in the future.)
